dao.usuario=com.uberits.accesodatos.jpa.DaoUsuarioJpa
dao.cliente=com.uberits.accesodatos.jpa.DaoClienteJpa
dao.restaurante=com.uberits.accesodatos.jpa.DaoRestauranteJpa
dao.plato=com.uberits.accesodatos.jpa.DaoPlatoJpa
dao.pedido=com.uberits.accesodatos.jpa.DaoPedidoJpa
dao.tipocomida=com.uberits.accesodatos.jpa.DaoTipoComidaJpa
dao.pedidolinea=com.uberits.accesodatos.jpa.DaoPedidoLineaJpa

validador=bibliotecas.validaciones.jakarta.ValidadorJakarta
validador.mapper=bibliotecas.validaciones.jakarta.ValidadorErroresMapperJakarta
